// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA7NijzNh9q99quS2Ohx1lHz9epbTFm_M',
    appId: '1:581425156970:web:eda83092547592fa6ccb13',
    messagingSenderId: '581425156970',
    projectId: 'pet-tracker-app-f06a4',
    authDomain: 'pet-tracker-app-f06a4.firebaseapp.com',
    storageBucket: 'pet-tracker-app-f06a4.firebasestorage.app',
    measurementId: 'G-ZBCK1TGM3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSdjm3oA8X60TuiXGid2p5n3HSuZdhs1k',
    appId: '1:581425156970:android:13fc8f40f941ed346ccb13',
    messagingSenderId: '581425156970',
    projectId: 'pet-tracker-app-f06a4',
    storageBucket: 'pet-tracker-app-f06a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNMlBXmDnl3jM_kh-IEyLelZXmtn0opoQ',
    appId: '1:581425156970:ios:7772bbaed42c900a6ccb13',
    messagingSenderId: '581425156970',
    projectId: 'pet-tracker-app-f06a4',
    storageBucket: 'pet-tracker-app-f06a4.firebasestorage.app',
    iosBundleId: 'com.example.myfirstapp',
  );
}
